spring:
  application:
    name: APIGATEWAY2

  cloud:
    discovery:
      enabled: true
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              uri: lb://PRODUCTSERVICE
              predicates:
                - Path=/products/**

            - id: order-service
              uri: lb://OrderService
              predicates:
                - Path=/orders/**

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: ${spring.application.name}

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

  prometheus:
    metrics:
      export:
        enabled: true
